rootUrl: http://127.0.0.1:9966
gridUrl: http://ondemand.saucelabs.com/wd/hub

plugins:
  sauce:
    username:
    accessKey:
  beefy:
    quiet: true
    entries:
      - page.js
    live: false
    watchify: false
    index: page.html
    bundlerFlags: '-t bulkify -p [css-modulesify -o dist/style.css]'

browsers:
  chrome:
    browserName: chrome
    platform: OS X 10.10
    version: '43.0'
  firefox:
    browserName: firefox
    platform: Linux
    version: '39.0'
  ie11:
    browserName: internet explorer
    platform: Windows 10
    version: '11.0'
  ie9:
    browserName: internet explorer
    platform: Windows 7
    version: '9.0'
