language: node_js
node_js:
  - '0.12'
sudo: false
addons:
  sauce_connect: true
  apt:
    packages:
    - graphicsmagick
env:
  global:
    - secure: Q+Z4VrgHAmkq1eClg9oICv7Z7HJ2w7wIlx0xBa0asXcWMP5zRMcqC0nWtibiTo+cs5pybkQKD08G8Yh+OA17t0tJGr4d7RDauUblVR9aAbaBQWs8PedtBzHnc8zSS9uQaJRTNAOS1B6iPL6wKxFKCmw+M2YPI/GJYDMjb3okTnSVLCTuvv5f9SS63IB39pMIkoO1XoS0d4UdTmPsy74+RnbX9iXE9emM5iBKfR17dpp7pi07LcOxH7E0KjDLIWCepfqTzokecnx3g8Gp9rhbCFGxXXPvpfdUGd/iarU9kKi25kaDUDF0ki+VgZGPbb3KxQ/932Qa4Vl+Mb0zZQHISX6RifwMPhm+Q2LB7ul3qMcIrguH/REuMLNGwn7nd0StZVCkLfIuVWR4ewz4YZL6zRgUdNXHnzb6aFGJYcJR8xeSOUT0sCFwFAU3V3LAbbTHK6e8OYZJDIt846xrqU6OdYGb4u6I0qPO/1w/O0bJ2gyBDYZGkc9aHkoBvELhFrvH6y3F+eGWu+2NIoslKFPyHlcXS3Y4W74c36SxCkgEATopVQzxjW3Z2H5GNTZbzPRSRohfs5j27mmQ3da7Fl6VWVq1haKrL48Tm87otsagaBk35eP4lKMTt+fTdnGoLTVqaRXXsRDAZLaaiPSQoUyv7EkIyHUbARun98JQEfhiB/w=
    - secure: WbTU7q3jJ4aMA0e64NnHfPrv9aEXE8F0a1wSX/D4iT1L/WRBy1wZDvhKisTBSE21xEw1qcaWjA6sShxRluqprHXSje05Jjl2MB2mDUbazNjM0fa0bpvhC+fRRfCeRc6GcasWYQJUXtSWBxdyOtrQx7T1Ecjc/BwDEh0jrJ4JQTdFFqtzjbhpF0yJQNRJCdT9LbPcrFNyEQhqrQIPmYeQ2enHpUZR4yfxxEbpx4wf817jKKlE7+Spykt9FlEeCyD1FkzhWWpern1yx5zrMoTawojyBEQLf4nFid8/d4nOOD8E9887Aokx30OKXuEKy96G0Co86w5w2lJa9DKJ5m1MPGdDV1kkDn74xJ6PCZOzES4p5qx9sCJyjbDyNjuf0oVu65Ue/C77oqgScBJNv/SAj/mwYPm+34dItP/r+ZIVGqmxFWZv8pY2PPOqxWW65N6FSs9TAnlsZNP0uUjsiDvn6lfIAAJUeR20lXQiD2u7Abi/Zco9M8fdCLb89AMdJ3QMC+ch2H7USVigJurs5ry4IYyD4MVhVOlmkVjL+3nVewinv598ZWzLRak7PzCbbxPsiTc/2e6ZDo7dtcYUefK8zeUEKUQ2KaAh4HpjL1eQsalVAPgfUdtKBX4WG2b+tYO2Xt5kTInPP+JXiAMl/Bdgpe2qnQ6ZpKCc8mvqFOVR8GY=
